name: Documentation update
description: Improve or correct documentation
title: "[docs] <short summary>"
labels: [documentation, needs-triage]
assignees: ["LarsGMortensen"]

body:
  - type: textarea
    id: context
    attributes:
      label: What needs to change?
      placeholder: "Page/section, incorrect snippet, missing example…"
    validations: { required: true }

  - type: textarea
    id: proposal
    attributes:
      label: Suggested edit
      placeholder: "Proposed wording/snippet. Link to file/line if possible."
