name: Performance issue
description: Report a regression or performance opportunity
title: "[perf] <short summary>"
labels: [performance, needs-triage]
assignees: ["LarsGMortensen"]

body:
  - type: textarea
    id: scenario
    attributes:
      label: Scenario
      placeholder: "Route/command, inputs, dataset size, env."
    validations: { required: true }

  - type: textarea
    id: metrics
    attributes:
      label: Metrics
      description: Provide numbers if possible (before/after, p95 TTFB, RSS, CPU ms).
      placeholder: "p95 TTFB +18%, RSS +12 MB, files included +30…"
    validations: { required: false }

  - type: textarea
    id: hypothesis
    attributes:
      label: Hypothesis / suspected cause
      placeholder: "Config merge hot path, reflection, I/O in constructor…"
