name: Set issue type (reusable)
on: workflow_call

permissions:
  issues: write

jobs:
  apply-type:
    runs-on: ubuntu-latest
    steps:
      - name: Decide and set type from labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT: ${{ toJson(github.event) }}
          REPO: ${{ github.repository }}
          NUM:  ${{ github.event.issue.number }}
        run: |
          labels=$(echo "$EVENT" | jq -r '[.issue.labels[].name] | join(",")')
          type=""
          echo "Labels: $labels"
          echo "$labels" | grep -qi '\bbug\b'     && type=bug
          echo "$labels" | grep -qi '\bfeature\b' && type=feature
          echo "$labels" | grep -qi '\btask\b'    && type=task

          if [ -n "$type" ]; then
            echo "Setting issue type: $type"
            gh api -X PATCH "/repos/$REPO/issues/$NUM" -f type="$type"
          else
            echo "No matching type; skipping."
          fi
